"""
=============================================================================
GitHub Issue Fetcher Agent - Main LangGraph Workflow
=============================================================================
This script defines a stateful ReAct (Reason + Act) agent built with LangGraph
and Ollama (running llama3.2 locally).

The agent can:
1. Converse naturally with the user.
2. Decide autonomously when to fetch GitHub issues from a repository.
3. Query issues assigned to specific developers.
4. Remember context across multiple conversational turns using memory.
=============================================================================
"""

import os
from typing import Annotated, Any, Dict, List, Sequence, TypedDict

from dotenv import load_dotenv
from langchain_core.messages import (
    AIMessage,
    BaseMessage,
    HumanMessage,
    SystemMessage,
    ToolMessage,
)
from langchain_core.tools import tool
from langchain_ollama import ChatOllama
from langgraph.checkpoint.memory import MemorySaver
from langgraph.graph import END, StateGraph
from langgraph.graph.message import add_messages
from langgraph.prebuilt import ToolNode

# Import GitHub API functions and repository configuration from githubAPI.py
from githubAPI import (
    GITHUB_TOKEN,
    OWNER,
    REPO,
    fetch_all_issues,
    fetch_all_isues,  # Backwards compatibility alias
    fetch_issues_assigned_to_user,
)


# =============================================================================
# 1. Agent State & Memory Definition
# =============================================================================
# CONCEPT: What is State in LangGraph?
# State is the central data structure (a Python TypedDict or Pydantic model)
# that is passed between every node in the graph. Nodes read from the state
# and return updates to it.
#
# CONCEPT: The 'messages' Reducer (`add_messages`)
# By default, updating a key in a TypedDict replaces its existing value.
# LangGraph uses `Annotated[Type, Reducer]` to customize how updates are applied:
# - Without a reducer: `state["messages"] = [new_message]` wipes out chat history!
# - With `add_messages`: LangGraph APPENDS new messages to the existing list,
#   preserving conversation history. It also supports updating existing messages
#   if their IDs match (upserting).
#
# CONCEPT: BaseMessage Hierarchy in LangChain
# A message sequence typically contains 4 core message types:
# 1. HumanMessage: Input provided by the user.
# 2. AIMessage: Output generated by the language model (text or tool calls).
# 3. SystemMessage: Instructions defining the agent's role, persona, and rules.
# 4. ToolMessage: Results returned by an executed tool (linked via tool_call_id).

class AgentState(TypedDict):
    """
    Represents the shared memory state of our agent throughout graph execution.
    
    Structure:
    {
        "messages": [
            SystemMessage(content="..."),
            HumanMessage(content="Show me open issues"),
            AIMessage(content="", tool_calls=[...]),
            ToolMessage(content="Found 3 issues...", tool_call_id="..."),
            AIMessage(content="Here are the 3 open issues...")
        ]
    }
    """
    messages: Annotated[Sequence[BaseMessage], add_messages]


# =============================================================================
# 2. Tools Definition
# =============================================================================
# CONCEPT: The @tool Decorator
# The @tool decorator wraps a standard Python function and generates a
# JSON Schema that the LLM can inspect. The LLM reads:
# 1. The function name.
# 2. The docstring (which explains WHEN and WHY to use the tool).
# 3. Parameter names, types, and descriptions.
#
# CONCEPT: Tool Error Handling
# Tools should catch exceptions and return readable error strings rather than
# crashing. This enables the LLM to understand what went wrong, adapt its
# parameters, or inform the user gracefully.

@tool
def get_all_repo_issues(state: str = "open") -> str:
    """
    Useful to get all issues from the configured GitHub repository.
    The 'state' parameter can be 'open', 'closed', or 'all'.
    """
    try:
        issues = fetch_all_issues(state=state)
        if not issues:
            return f"No {state} issues found in {OWNER}/{REPO}."

        output = [f"Found {len(issues)} issues in {OWNER}/{REPO}:"]
        for issue in issues:
            assignees_str = ", ".join(issue['assignees']) if issue['assignees'] else "None"
            output.append(
                f"#{issue['number']} - {issue['title']} "
                f"(Author: {issue['author']}, Assignees: [{assignees_str}], State: {issue['state']}, URL: {issue['url']})"
            )
        return "\n".join(output)
    except Exception as e:
        return f"Error fetching repository issues: {str(e)}"


@tool
def get_issues_assigned_to_user(username: str, state: str = "all") -> str:
    """
    Useful to find GitHub issues assigned to a specific username in the repository.
    The 'state' parameter can be 'open', 'closed', or 'all'.
    """
    try:
        issues = fetch_issues_assigned_to_user(username=username, state=state)
        if not issues:
            return f"No issues found assigned to user '{username}' in {OWNER}/{REPO}."

        output = [f"Found {len(issues)} issues assigned to {username}:"]
        for issue in issues:
            output.append(
                f"#{issue['number']} - {issue['title']} "
                f"(State: {issue['state']}, URL: {issue['url']})"
            )
        return "\n".join(output)
    except Exception as e:
        return f"Error fetching issues for user '{username}': {str(e)}"


# Bundle tools into a list for the agent
tools = [get_all_repo_issues, get_issues_assigned_to_user]


# =============================================================================
# 3. LLM Configuration & Tool Binding
# =============================================================================
# CONCEPT: Local LLM with ChatOllama
# We use Ollama to run models (like llama3.2) entirely locally on our machine.
#
# CONCEPT: Tool Binding (.bind_tools)
# Calling `.bind_tools(tools)` converts our Python tools into the OpenAI-compatible
# tool calling schema. This instructs the LLM that it has the ability to invoke
# these specific functions when it needs external information.
#
# CONCEPT: Temperature
# Temperature controls randomness (0.0 = deterministic, 1.0 = creative).
# For tool-calling agents, a low temperature (0.1 - 0.3) ensures reliable,
# consistent argument generation without hallucinations.

llm = ChatOllama(model="llama3.2", temperature=0.3).bind_tools(tools)


# =============================================================================
# 4. Graph Nodes & Routing Functions
# =============================================================================

def model_call(state: AgentState) -> Dict[str, List[BaseMessage]]:
    """
    Primary agent node: Receives current state, prepends the system prompt,
    invokes the LLM with the message history, and returns the LLM's response.
    """
    # System prompt guides the agent's role and behavior
    system_prompt = SystemMessage(
        content=(
            f"You are a helpful GitHub issue management assistant for the repository '{OWNER}/{REPO}'. "
            "Use the provided tools to retrieve and summarize repository issues. "
            "Always be clear, concise, and informative in your responses."
        )
    )

    # Prepend the system prompt to the accumulated conversation history
    messages = [system_prompt] + list(state["messages"])
    response = llm.invoke(messages)

    # Return the update dict. LangGraph's add_messages reducer appends this response to state["messages"]
    return {"messages": [response]}


def should_continue(state: AgentState) -> str:
    """
    Conditional edge router: Decides the next step after the LLM responds.
    
    Logic:
    - If the LLM returned tool calls -> Route to the 'tools' node.
    - If the LLM returned a direct text response -> Route to END (finish turn).
    """
    last_message = state["messages"][-1]

    # Check if the model requested any tool executions
    if hasattr(last_message, "tool_calls") and last_message.tool_calls:
        return "tools"
    return END


# =============================================================================
# 5. Graph Assembly & Compilation
# =============================================================================
# CONCEPT: The ReAct Graph Loop
#
#                     [START]
#                        │
#                        ▼
#               ┌────────────────┐
#               │   our_agent    │ ◄──────────┐
#               └───────┬────────┘            │
#                       │                     │
#                       ▼                     │
#               should_continue               │
#                 /           \               │
#        (has tool calls)  (no tool calls)    │
#               /               \             │
#              ▼                 ▼            │
#       ┌─────────────┐       [ END ]         │
#       │    tools    │                       │
#       └──────┬──────┘                       │
#              │                              │
#              └──────────────────────────────┘
#                (tool output added to state)
#
# 1. User inputs a query.
# 2. 'our_agent' runs the LLM to decide what to do (Reasoning).
# 3. 'should_continue' checks if a tool call was requested:
#    - If YES: Routes to 'tools' node (ToolNode executes the Python function).
#    - Tool results are appended to state as ToolMessage.
#    - Graph loops back to 'our_agent' so the LLM can interpret tool output.
#    - If NO: The LLM formulated the final answer; graph exits to END.

# Initialize the StateGraph with our state schema
graph = StateGraph(AgentState)

# Add nodes to the graph
graph.add_node("our_agent", model_call)
graph.add_node("tools", ToolNode(tools=tools))

# Define graph flow and edges
graph.set_entry_point("our_agent")
graph.add_conditional_edges(
    "our_agent",
    should_continue,
    {
        "tools": "tools",
        END: END,
    }
)
graph.add_edge("tools", "our_agent")

# CONCEPT: MemorySaver Checkpointer
# Compiling the graph with a checkpointer enables multi-turn conversation memory!
# All state updates are persisted per session 'thread_id'.
checkpointer = MemorySaver()
app = graph.compile(checkpointer=checkpointer)


# =============================================================================
# 6. Interactive Multi-Turn Chat Loop
# =============================================================================

def run_chat_loop():
    """
    Runs an interactive multi-turn command-line chat session with the GitHub agent.
    Retains message history across turns using LangGraph's checkpointer.
    """
    # Configure a session thread ID for conversation memory
    thread_config = {"configurable": {"thread_id": "github_agent_session_1"}}

    print("\n" + "=" * 65)
    print("🐙 GitHub Issue Fetcher Agent (LangGraph + Ollama)")
    print("=" * 65)
    print(f"Target Repository : {OWNER}/{REPO}")
    print("Commands          : Type 'exit', 'quit', or 'q' to end the chat.")
    print("=" * 65 + "\n")

    while True:
        try:
            # Prompt user for input
            user_input = input("You: ").strip()

            # Check for exit condition
            if not user_input:
                continue
            if user_input.lower() in ["exit", "quit", "q"]:
                print("\n👋 Goodbye! Thank you for using GitHub Issue Fetcher Agent.\n")
                break

            # Stream graph execution so user sees actions and final response
            input_data = {"messages": [HumanMessage(content=user_input)]}

            print("\n[Agent Thinking...]")
            for step in app.stream(input_data, config=thread_config, stream_mode="values"):
                latest_message = step["messages"][-1]

                # Check for tool calls or final AI message
                if isinstance(latest_message, AIMessage):
                    if latest_message.tool_calls:
                        for tool_call in latest_message.tool_calls:
                            print(f"⚙️  Calling Tool: {tool_call['name']}({tool_call['args']})")
                    elif latest_message.content:
                        print(f"\nAgent: {latest_message.content}\n")
                elif isinstance(latest_message, ToolMessage):
                    print("✅ Tool execution completed. Summarizing results...")

        except KeyboardInterrupt:
            print("\n\nSession interrupted. Exiting...")
            break
        except Exception as e:
            print(f"\n❌ An error occurred: {e}\n")


if __name__ == "__main__":
    run_chat_loop()